### ISSUE TITLE
[TEST] 전체적인 테스트코드 작성

### ISSUE THREAD

**Issue by CokeLee777** [MOKY4/hollang-weeks52-api-server#11]
## Description

설명을 작성하세요.

## To-do
- [x] Repository 테스트 작성 
- [x] Service 테스트 작성 
- [x] Controller 테스트 작성
