### ISSUE TITLE
[REFACTOR] 기능 개선에 따른 리팩터링

### ISSUE THREAD

**Issue by CokeLee777** [MOKY4/hollang-weeks52-api-server#4]
## Description

기능 개선에 따른 리팩터링

1. 취미 유형 테이블 3D 이미지 제거
2. 취미 테이블 요약정보 추가
3. 카카오톡 공유하기 API 추가

## To-do
- [x] Entity 구조 및 속성 변경
- [x] DAO 로직 개선
- [x] 서비스 로직 개선
