### ISSUE TITLE
[REFACTOR] API 로직 리팩터링 및 기능개선

### ISSUE THREAD

**Issue by CokeLee777** [MOKY4/hollang-weeks52-api-server#6]
## Description

API 로직 리팩터링 및 기능개선

## To-do
- [x] Entity 로직 개선
- [x] DAO 및 서비스 로직 개선
- [x] 구조 개선
- [x] 테스트 코드 작성
