### ISSUE TITLE
[FEATURE] Query 성능 최적화

### ISSUE THREAD

**Issue by CokeLee777** [MOKY4/hollang-weeks52-api-server#9]
## Description

각 API 호출에 따른 쿼리 성능 최적화

## To-do
- [x] 테스트 응답 API 쿼리 성능 최적화
- [x] 추천 API 쿼리 성능 최적화
- [x] 추천 공유하기 페이지 API 쿼리 성능 최적화
- [x] 추천 설문조사 API 쿼리 성능 최적화
